# The file is generated by Claude Code

"""Build docs/polars_patch.inv — a patch for polars' broken objects.inv.

The polars Sphinx inventory is missing py:class entries for all major classes
(DataFrame, LazyFrame, Series, Expr, Config, DataType). Their docs build
generates per-method pages and never emits the class-level entry.

This script constructs a small supplemental inventory with just those six
entries, each pointing to the relevant class overview page.

Usage:
    uv run --with sphobjinv build_polars_patch_inv.py
"""

import pathlib
import sphobjinv as soi

OUT = pathlib.Path(__file__).parent / "docs" / "polars_patch.inv"

# Mapping: fully-qualified name -> relative URL (from docs.pola.rs/api/python/stable/)
# $ means "use the object name as the anchor" (standard Sphinx convention)
MISSING_CLASSES = {
    "polars.Config":    "reference/config.html#$",
    "polars.DataFrame": "reference/dataframe/index.html#$",
    "polars.DataType":  "reference/datatypes.html#$",
    "polars.Expr":      "reference/expressions/index.html#$",
    "polars.LazyFrame": "reference/lazyframe/index.html#$",
    "polars.Series":    "reference/series/index.html#$",
}

objects = [
    soi.DataObjStr(
        name=name,
        domain="py",
        role="class",
        priority="1",
        uri=uri,
        dispname="-",
    )
    for name, uri in MISSING_CLASSES.items()
]

inv = soi.Inventory()
inv.project = "polars-patch"
inv.version = ""
inv.objects = objects

soi.writebytes(str(OUT), soi.compress(inv.data_file()))
print(f"Written {len(objects)} entries to {OUT}")
